apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-deployment
  labels:
    app: ctse-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctse-app
  template:
    metadata:
      labels:
        app: ctse-app
    spec:
      containers:
        - name: ctse-app
          image: randi480/supplier-management-ms:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
