apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  type: LoadBalancer # give access externally through a cloud provider's load balancer functionality
  ports:
    - name: http
      port: 80 # port exposed internally in the cluster
      protocol: TCP
      targetPort: 3000 # the container port to send requests to
  selector:
    app: ctse-app # "select pods with the label 'app' set to 'ctse-app'"
  sessionAffinity: None
