apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-deployment
  labels:
    app: ctse-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ctse-app
  template:
    metadata:
      labels:
        app: ctse-app
    spec:
      containers:
        - name: ctse-app
          image: randi480/supplier_management_ms:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
